name: Java CI with Maven

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'maven'

    - name: Set up Maven
      run: sudo apt-get install -y maven  # Replace with appropriate command for your environment

    - name: Build with Maven
      run: mvn clean install
