on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y \
        wget \
        unzip \
        xvfb \
        libxi6 \
        libgconf-2-4 \
        default-jdk \
        google-chrome-stable

    - name: Set up ChromeDriver
      run: |
        wget -N https://chromedriver.storage.googleapis.com/91.0.4472.101/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv -f chromedriver /usr/local/share/chromedriver
        sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
        sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver

    - name: Run xvfb
      run: |
        Xvfb :99 -ac &
        export DISPLAY=:99

    - name: Run tests
      run: mvn clean install
