name: Java CI with Maven

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'maven'

    - name: Install Chrome
      run: |
        choco install googlechrome --ignore-checksums

    - name: Install Chromedriver
      run: |
        choco install chromedriver --ignore-checksums

    - name: Verify Chromedriver installation
      run: |
        chromedriver --version

    - name: Build with Maven
      run: mvn clean install
