name: Java CI with Maven

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'maven'

    - name: Download ChromeDriver
      run: |
        # Specific version of ChromeDriver
        $chromeVersion = "126.0.6478.126"
        Invoke-WebRequest -Uri "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$chromeVersion/win64/chromedriver-win64.zip" -OutFile "chromedriver_win64.zip"
        Expand-Archive chromedriver_win64.zip -DestinationPath .
        Remove-Item -Force chromedriver_win64.zip
        $env:PATH += ";$(pwd)\chromedriver-win64"

    - name: Verify ChromeDriver installation
      run: |
        .\chromedriver-win64\chromedriver.exe --version

    - name: Build with Maven
      run: mvn clean install
