name: Java CI with Maven

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'maven'

    # - name: Google Chrome Setup
    #   run: |
    #     sudo apt-get install -y gnupg
    #     sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    #     sudo echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
    #     sudo apt-get -y update
    #     sudo apt-get -y install google-chrome-stable  

    - name: Googledriver setup
      run: |
        sudo apt install wget -y
        sudo apt install unzip -y
        wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip  
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chown runner:runner /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver  

    - name: Set up Maven
      run: sudo apt-get install -y maven        
      
    - name: Build with Maven
      run: |
        ls -la
        pwd
        mvn clean install
