name: Java CI with Maven

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'maven'

    - name: Create .m2 directory
      run: mkdir -p ~/.m2

    - name: Fix permissions for .m2 directory
      run: chmod -R 777 ~/.m2

    # - name: Update apt-get
    #   run: apt-get update

    # - name: Fix broken dependencies
    #   run: apt --fix-broken install -y

    # - name: Set up Maven and dependencies
    #   run: |
    #     apt-get update
    #     apt-get install -y libasound2 libasound2-data libnspr4 libnss3 default-jre-headless libjansi-java libmaven3-core-java libwagon-file-java libwagon-http-shaded-java

    - name: Googledriver setup
      run: |
        apt install wget -y
        apt install unzip -y
        wget https://dl.google.com/linux/deb/pool/main/g/google-chrome-stable/google-chrome-stable_126.0.6478.126-1_amd64.deb
        dpkg -i google-chrome-stable_126.0.6478.126-1_amd64.deb
        wget https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.126/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip  
        mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
        chown runner:runner /usr/bin/chromedriver
        chmod +x /usr/bin/chromedriver

    # - name: Debug info
    #   run: |
    #     echo "Java version:"
    #     java -version
    #     echo "Chrome version:"
    #     google-chrome --version
    #     echo "ChromeDriver version:"
    #     chromedriver --version
    #     echo "Current directory:"
    #     pwd
    #     echo "Contents of /usr/bin:"
    #     ls -la /usr/bin
    #     echo "Contents of /usr/local/bin:"
    #     ls -la /usr/local/bin

    - name: Install xvfb
      run: apt-get install -y xvfb

    - name: Start xvfb
      run: |
        export DISPLAY=:99
        xvfb-run -a mvn clean install -Dbrowser=chrome

